-- sequences
CREATE SEQUENCE teachersSeq;
CREATE SEQUENCE coursesSeq;

-- teachers table
CREATE TABLE teachers (
    idTeacher INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255));

-- courses table
CREATE TABLE courses (
    idCourse INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    title VARCHAR(255), 
    teacher VARCHAR(255), 
    level VARCHAR(32), 
    hoursLong FLOAT, 
    active BOOLEAN);