CREATE TABLE courses (
    idCourse BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    title VARCHAR(255), 
    teacher VARCHAR(255), 
    level VARCHAR(32), 
    hoursLong FLOAT, 
    active BOOLEAN);