-- teachers table
CREATE TABLE teachers (
    idTeacher BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255));

-- courses table
CREATE TABLE courses (
    idCourse BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
    title VARCHAR(255), 
    teacher VARCHAR(255), 
    level VARCHAR(32), 
    hoursLong FLOAT, 
    active BOOLEAN);